# Challenge 1: Geodemographic Classification

In this challenge, you will replicate the process of creating a geodemographic classification using the k-means clustering algorithm. Please select any city in the UK except London, Liverpool, or Glasgow. The main goal is to generate a meaningful and informative classification that captures the diversity of areas in your dataset using the census data ( For England, you can try to use the 2021 or 2011 census, and for Scotland, you need to use the 2011 census data) 

1. Define the main goal for the geodemographic classification (marketing, retail and service planning). 
2. Look for census data from the selected city for which you would like to generate the geodemographic classification.
3. The census data at the Output Area OA level. Select multiple topics of at least four topics (socio-demographics, economics, health, and so on). Describe your topic selection accordingly based on the goal of your geodemographic classification. For example, if your geodemographics are related to marketing, Economic variables might be the appropriate selection. 
4. Identify the variables that will be crucial for effectively segmenting neighbourhoods. Evaluate how this choice may impact the classification results, including a DEA analysis.
5. Prepare, adjust or clean the dataset addressing any missing values or outliers that could distort the clustering results.
6. Include standardisation between areas and variables. Make an appropriate analysis and adjust the variable selection accordingly for any multicollinearity.
7. Utilize the k-means clustering algorithm to create a classification based on the selected variables.
8. Define the optimum number of clusters (i.e., using the Elblow method). Experiment with different values of k.
9. Evaluate your cluster groups (e.g., using PCA) and interpret your cluster centres. Describe your results and repeat the process to adjust the variable selection and cluster groups to provide more meaningful results for your geodemographic goal. Interpret the characteristics of each cluster. What demographic patterns or similarities are prevalent within each group?
10. Map the final cluster groups
11. Finish the analysis by naming the final clusters and plotting a final map that includes the census values and the provided names.
12. Finally, acknowledge the subjective nature of classification and make analytical decisions to produce an optimum classification for your specific purpose. Reflect on the challenges and insights gained during the classification process. Ensure you document your analytical decisions and the rationale behind any important decision. Once your geodemographics are constructed, describe the potential use cases for the geodemographic classification you have built based on your initial goal.

In [ ]:
#defining the main goal for the geodemographic classification

I will be examining data for the city of Brigthton and Hove from a marketing perspective using data from the 2021 Census for England and Wales.

**Study area**: Brighton and Hove
**Geography (spatial units)** Output Areas 
**Dataset**: 2021 United Kingdom Census 

**Census Variables Used** - 
- Age structure
- Economic activity
- Hours worked
- Industry
- Marital and civil partnership status
- Religion
- Sex

Reference: ONS (2021). Census - Office for National Statistics. [online] Ons.gov.uk. Available at: https://www.ons.gov.uk/census.

In [ ]:
#identifying variables to help with a marketing analysis

In [ ]:
#preparing the variables for analysis

In [43]:
#loading in our csv files
import pandas as pd
import os

csv_directory = "data/raw_data"

csv_files = [file for file in os.listdir(csv_directory) if file.endswith(".csv")]

In [44]:
#creating an empty dataframe to merge the csv files
merged_census_data = pd.DataFrame()

In [45]:
#looping through CSV files
for csv_file in csv_files:
    csv_path = os.path.join(csv_directory, csv_file) #creating a consistent path
    df_csv = pd.read_csv(csv_path, low_memory=False) #reading each file
    merged_census_data = pd.concat([merged_census_data, df_csv], axis=1) #concatenating all columns, duplicate oa_codes will have to be eliminated

In [54]:
#saving the new merged data
merged_census_data.to_csv("data/raw_data/merged_census_data.csv", index=False)

In [55]:
#exploring the new merged dataframe
merged_census_data.head(3)

,OA,Output Areas,Age (B) (4 categories) Code,Age (B) (4 categories),Observation,Output Areas Code,Output Areas,Economic activity status (7 categories) Code,Economic activity status (7 categories),Observation,...,Output Areas Code,Output Areas,Marital and civil partnership status (6 categories) Code,Marital and civil partnership status (6 categories),Observation,Output Areas Code,Output Areas,Sex (2 categories) Code,Sex (2 categories),Observation
0,E00000001,E00000001,1.0,Aged 15 years and under,15.0,E00000001,E00000001,-8.0,Does not apply,15.0,...,E00000001,E00000001,-8.0,Does not apply,15.0,E00000001,E00000001,1.0,Female,75.0
1,E00000001,E00000001,2.0,Aged 16 to 49 years,55.0,E00000001,E00000001,1.0,Economically active (excluding full-time stude...,88.0,...,E00000001,E00000001,1.0,Never married and never registered a civil par...,34.0,E00000001,E00000001,2.0,Male,101.0
2,E00000001,E00000001,3.0,Aged 50 to 64 years,40.0,E00000001,E00000001,2.0,Economically active (excluding full-time stude...,10.0,...,E00000001,E00000001,2.0,Married or in a registered civil partnership,97.0,E00000003,E00000003,1.0,Female,123.0

In [35]:
#we now make a filter to only work with Brighton and Hove output areas

#first, reading in our shapefile of all output areas for the UK
import geopandas as gpd

shp_path = "data/raw_data/OA_2021_EW_BGC_V2.shp"
gdf = gpd.read_file(shp_path)
gdf.head()

,OA21CD,LSOA21CD,LSOA21NM,LSOA21NMW,BNG_E,BNG_N,LAT,LONG,GlobalID,geometry
0,E00000001,E01000001,City of London 001A,None,532250,181864,51.5202,-0.09523,3a44dd3d-5082-4a09-9b9c-3a5fadc811ed,"POLYGON ((532303.492 181814.11, 532213.378 181..."
1,E00000003,E01000001,City of London 001A,None,532171,181819,51.5198,-0.09638,f1216dc8-14d1-4857-9230-cab0641758fb,"POLYGON ((532213.378 181846.192, 532190.539 18..."
2,E00000005,E01000001,City of London 001A,None,532166,181722,51.5190,-0.09649,44d6f70f-549c-4288-9b6d-de2adbf02582,"POLYGON ((532180.131 181763.02, 532219.161 181..."
3,E00000007,E01000001,City of London 001A,None,532088,181473,51.5167,-0.09771,4dd683e1-9a5c-46cf-9e19-8465c8fbb6cb,"POLYGON ((532201.292 181668.18, 532267.728 181..."
4,E00000010,E01000003,City of London 001C,None,532092,182114,51.5225,-0.09741,7476781f-8fe4-4c9b-bde1-0eecbd146dff,"POLYGON ((532127.958 182133.192, 532089.264 18..."

In [59]:
#how many output areas there are 
gdf.shape

(936, 10)

In [36]:
#checking out the gdf column titles
print(gdf.columns)

Index(['OA21CD', 'LSOA21CD', 'LSOA21NM', 'LSOA21NMW', 'BNG_E', 'BNG_N', 'LAT',
       'LONG', 'GlobalID', 'geometry'],
      dtype='object')

In [ ]:
#removing duplicates from gdf

In [37]:
#searching for Brighton and Hove
brighton_hove_rows = gdf[gdf["LSOA21NM"].str.contains("Brighton|Hove", case=False, na=False)]
brighton_hove_rows.head()

,OA21CD,LSOA21CD,LSOA21NM,LSOA21NMW,BNG_E,BNG_N,LAT,LONG,GlobalID,geometry
80263,E00085001,E01016852,Brighton and Hove 026B,None,529776,104607,50.8265,-0.15873,f344c9c4-ab5e-4908-83d8-6afcc7ee0b17,"POLYGON ((529813.436 104652.842, 529785 104516..."
80264,E00085002,E01016852,Brighton and Hove 026B,None,529632,104503,50.8256,-0.16081,63969c3d-b4c4-4f6c-9523-b9f826a11c3c,"POLYGON ((529600 104563, 529702.871 104531.025..."
80265,E00085003,E01016850,Brighton and Hove 029A,None,529936,104439,50.8249,-0.15652,b769cd64-c3c9-4bc3-9968-f1f58e718ea1,"POLYGON ((530000.031 104482.116, 530016.999 10..."
80266,E00085005,E01016850,Brighton and Hove 029A,None,529837,104310,50.8238,-0.15797,7a103ec3-7492-4a98-ad27-a24d13a7c016,"POLYGON ((529898.327 104377.927, 529871.691 10..."
80267,E00085006,E01016853,Brighton and Hove 026C,None,529485,104756,50.8279,-0.16281,f1121dba-7400-46d4-8d73-90fcecaac265,"POLYGON ((529491.999 104828.11, 529561.05 1048..."

In [38]:
#saving Brighton and Hove output areas as a shapefile
brighton_hove_rows.to_file("data/raw_data/brighton_hove_output_areas.shp")

In [39]:
#loading the filtered shapefile
filtered_shapefile = "data/raw_data/brighton_hove_output_areas.shp"
gdf = gpd.read_file(filtered_shapefile)

In [40]:
#plotting the shapefile
gdf.plot

In [51]:
#merging our merged, cleaned census data with the gdf of Brighton and Hove output areas

In [56]:
# merge the GeoDataFrame with the DataFrame based on the oa_code
merged_data = gdf.merge(merged_census_data, left_on='OA21CD', right_on='OA', how='left')
merged_data.to_file('data/brighton_census.shp', index=False) #also saving merged census data as a shapefile

C:\Users\user\AppData\Local\Temp\ipykernel_13748\2604390606.py:3: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  merged_data.to_file('data/brighton_census.shp', index=False) #also saving merged census data as a shapefile

ValueError: GeoDataFrame cannot contain duplicated column names.

In [57]:
shp_path = "data/brighton_census.shp"
shp = gpd.read_file(shp_path)

In [58]:
shp.plot

In [ ]:
#DEA Analysis

In [ ]:
#standardisation